# Generated by Django 3.2.5 on 2021-12-14 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twowaypermission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twp_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
